chore(updatedependencies): update various dependencies
americanexpress/amex-jest-preset pull request #58
Opened 2022-12-13 17:51 UTC by dogpatch626

updated various dependencies. 
## Description

```
    "@commitlint/cli": "^9.1.2",
    "@commitlint/config-conventional": "^17.3.0",
    "@semantic-release/changelog": "^6.0.0",
    "@semantic-release/commit-analyzer": "^9.0.0",
    "@semantic-release/git": "^10.0.0",
    "@semantic-release/github": "^8.0.0",
    "@semantic-release/npm": "^9.0.0",
    "@semantic-release/release-notes-generator": "^10.0.0",
    "eslint-config-amex": "^15.3.1",
    "jest": "^29.0.0",
    "semantic-release": "^19.0.0"
    ```
    after updating these packages running npm audit showed 0 vulnerabilities. 
## Motivation and Context

## How Has This Been Tested?
ran unit tests, they pass needed to update snapshots they're appropriate just a change in back slashes present.
also installed into one app and ran unit tests 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] My changes are in sync with the code style of this project.
- [ ] There aren't any other open Pull Requests for the same issue/update.
- [ ] These changes should be applied to a maintenance branch.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using amex-jest-preset?

2022-12-13 18:18 UTC, Matthew-Mallimo approved these changes

2022-12-13 18:18 UTC, Matthew-Mallimo commented
Looks like there are conflicts in the package-lock

2022-12-13 18:19 UTC, Matthew-Mallimo requested changes
Fix package-lock issues

2023-01-03 14:29 UTC, Matthew-Mallimo approved these changes

2023-01-12 20:53 UTC, giulianok approved these changes

2023-01-13 04:50 UTC, 10xLaCroixDrinker approved these changes

2023-01-13 04:53 UTC, merged